#!/usr/bin/env bash
# Build llms-full.txt at the repository root.
#
# Concatenates the ELPX-format documentation set plus architecture and
# conventions into a single file for LLMs that prefer one document over
# following links. The companion /llms.txt stays as the index per
# https://llmstxt.org/.
#
# Re-run whenever any of the listed docs change.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$REPO_ROOT/llms-full.txt"

cd "$REPO_ROOT"

# Ordered list of docs to inline. Order is the natural reading order: hub
# first, then container/structure, then iDevices, then resources, then
# pipelines/validation, then AI generation, then examples, then project
# context.
FILES=(
    "doc/elpx-format.md"
    "doc/elpx-format/container.md"
    "doc/elpx-format/content-xml.md"
    "doc/elpx-format/ids.md"
    "doc/elpx-format/metadata.md"
    "doc/elpx-format/pages-blocks.md"
    "doc/elpx-format/idevices/catalog.md"
    "doc/elpx-format/idevices/patterns.md"
    "doc/elpx-format/idevices/config-xml.md"
    "doc/elpx-format/idevices/snippets.md"
    "doc/elpx-format/themes.md"
    "doc/elpx-format/libraries.md"
    "doc/elpx-format/assets.md"
    "doc/elpx-format/screenshot.md"
    "doc/elpx-format/export-pipeline.md"
    "doc/elpx-format/import-pipeline.md"
    "doc/elpx-format/validation.md"
    "doc/elpx-format/ai-generation.md"
    "doc/elpx-format/examples/minimal-content-xml.md"
    "doc/elpx-format/examples/multi-page-content-xml.md"
    "doc/elpx-format/examples/full-package-tree.md"
    "doc/architecture.md"
    "doc/conventions.md"
)

{
    cat <<'HEADER'
# eXeLearning — Full Documentation Bundle

> This is a single-file concatenation of the eXeLearning ELPX-format
> documentation set, plus the project's architecture and conventions
> documents. It is generated by `scripts/build-llms-full.sh` from the
> Markdown sources under `doc/`. Use this file when a context window
> prefers one large document over following links from `/llms.txt`.

> Source files (in order):
HEADER

    for f in "${FILES[@]}"; do
        printf -- '> - `%s`\n' "$f"
    done

    printf '\n---\n'

    for f in "${FILES[@]}"; do
        if [[ -f "$f" ]]; then
            printf '\n\n# ===== %s =====\n\n' "$f"
            cat "$f"
        else
            printf '\n\n# ===== %s =====\n\n' "$f"
            printf '> _(file not found at build time; skipped)_\n'
        fi
    done

    printf '\n'
} > "$OUT"

LINES=$(wc -l < "$OUT" | tr -d ' ')
SIZE=$(wc -c < "$OUT" | tr -d ' ')

printf 'Built %s (%s lines, %s bytes)\n' "$OUT" "$LINES" "$SIZE"
